### ISSUE TITLE
java.lang.NoClassDefFoundError: scala/Serializable

### ISSUE THREAD

**Issue by mailvdutt** [SAP/kafka-connect-sap#137]
I am trying to use the kafka-connect-sap  to connect to sap Hana on-premises and load data into Kafka on the confluent azure cloud.Source connector fails to start

*********************source properties file *********************

name=hana_invoice_header_source**
#connector.class=11com.sap.kafka.connect.source.hana.HANASourceConnector
connector.class=com.sap.kafka.connect.source.hana.HANASourceConnector
tasks.max=1
topics=hana_invoice_header
connection.url=jdbc:sap://10.0.20.15:30315/
connection.user="ODBCHANA"
connection.password="Sym1!ODBC"
#hana_invoice_header.table.name=NEBSAP::INVOICE_HEADER
hana_invoice_header.table.name="SYS"."DUMMY"
~                                                                 

(org.apache.kafka.connect.runtime.SourceConnectorConfig:376)
[2022-11-06 22:08:33,484] INFO [hana_invoice_header_source|worker] EnrichedConnectorConfig values:
        config.action.reload = restart
        connector.class = com.sap.kafka.connect.source.hana.HANASourceConnector
        errors.log.enable = false
        errors.log.include.messages = false
        errors.retry.delay.max.ms = 60000
        errors.retry.timeout = 0
        errors.tolerance = none
        header.converter = null
        key.converter = null
        name = hana_invoice_header_source
        predicates = []
        tasks.max = 1
        topic.creation.groups = []
        transforms = []
        value.converter = null
 (org.apache.kafka.connect.runtime.ConnectorConfig$EnrichedConnectorConfig:376)
[2022-11-06 22:08:33,488] INFO [hana_invoice_header_source|worker] Instantiated connector hana_invoice_header_source with version 0.9.4 of type class com.sap.kafka.connect.source.hana.HANASourceConnector (org.apache.kafka.connect.runtime.Worker:310)
[2022-11-06 22:08:33,489] INFO [hana_invoice_header_source|worker] Finished creating connector hana_invoice_header_source (org.apache.kafka.connect.runtime.Worker:335)
[2022-11-06 22:08:33,495] ERROR [hana_invoice_header_source|worker] WorkerConnector{id=hana_invoice_header_source} Error while starting connector (org.apache.kafka.connect.runtime.WorkerConnector:193)
java.lang.NoClassDefFoundError: scala/Serializable
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:555)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
        at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:95)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at com.sap.kafka.connect.source.hana.HANASourceConnector.start(HANASourceConnector.scala:25)
        at org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:185)
        at org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:210)
        at org.apache.kafka.connect.runtime.WorkerConnector.doTransitionTo(WorkerConnector.java:349)
        at org.apache.kafka.connect.runtime.WorkerConnector.doTransitionTo(WorkerConnector.java:332)
        at org.apache.kafka.connect.runtime.WorkerConnector.doRun(WorkerConnector.java:141)
        at org.apache.kafka.connect.runtime.WorkerConnector.run(WorkerConnector.java:118)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: scala.Serializable
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:103)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 22 more

**Comment by AndreasFischbach3003** [comment]
Did you specify the pluginpath correctly?

**Comment by mailvdutt** [comment]
Yes plugin path is correct and the below jar files are available in the
plugin path

ls -lrt plugins/kafka-connector-hana

total 1536

-rw-r--r--. 1 vdutt vdutt  204062 Nov  6 19:47
*kafka-connector-hana_2.12-0.9.5-SNAPSHOT.jar*

-rw-r--r--. 1 vdutt vdutt   44642 Nov  6 19:48
*kafka-connector-hana_2.12-0.9.5-SNAPSHOT-sources.jar*

-r--r--r--. 1 vdutt vdutt 1319347 Nov  6 19:49 *ngdbc.jar*

**Comment by elakito** [comment]
@mailvdutt The class that was not found scala.Serializable is one of the fundamental classes from scala-library-2.xx.jar. So, usually every plugin should be able to find this class without any magic. Which kafka scala version is used in your kafka connect instance? Maybe you picked the wrong kafka-connect-hana scala lib version and there is a mismatch?

**Comment by AndreasFischbach3003** [comment]
do you  have the ngdbc-x.x.x.jar  in your plugin directory?

**Comment by mailvdutt** [comment]
Yes   ngdbc-x.x.x.jar  Is in plug-in directory Sent from my iPhoneOn Nov 8, 2022, at 3:06 AM, AndreasFischbach3003 ***@***.***> wrote:﻿
do you  have the ngdbc-x.x.x.jar  in your plugin directory?

**Comment by elakito** [comment]
@mailvdutt Your yesterday's posting shows ngdbc.jar but today's posting doesn't show ngdbc.jar. So, maybe I am wondering that if this file was mistakenly removed when you replaced the kafka-connector-hana_2.12-xxx.jar with kafka-connector-hana_2.13-xxx.jar. By the way, you don't need the source jar in your plugin folder. And Could you tell us which version of  ngdbc.jar you are using? This jar, in its original form, should have the version number in the file name. Maybe someone might have repackaged the content of this jar and some classes are missing?

**Comment by mailvdutt** [comment]
I am downloaded from
https://tools.hana.ondemand.com/additional/hanaclient-latest-linux-x64.tar.gz
then extracted sudo tar -xzf hanaclient-latest-linux-x64.tar.gz

*ngdbc.jar file does exist in the plugin folder*
*Also i tested *java -jar ngdbc.jar  -u and was able to connect by just
using the jar file

***@***.*** kafka-connector-hana]$ ls -lrt

total 1536

-r--r--r--. 1 vdutt vdutt 1319347 Nov  6 19:49 *ngdbc.jar*

-rw-r--r--. 1 vdutt vdutt  203849 Nov  7 18:47
*kafka-connector-hana_2.13-0.9.5-SNAPSHOT.jar*

-rw-r--r--. 1 vdutt vdutt   44635 Nov  7 18:47
*kafka-connector-hana_2.13-0.9.5-SNAPSHOT-sources.jar*

***@***.*** kafka-connector-hana]$

**Comment by elakito** [comment]
I thought maybe there is some problem with some kafka versions. So, I just tried it out using ngdbc.jar extracted from hanaclient-latest-linux-x64.tar.gz with various kafka connect versions of kafka_2.13-2.8.2, kafka_2.13-3.0.2, kafka_2.13-3.1.2, kafka_2.13-3.2.3 (using the standalone setup described in examples/persons1), it is working fine. 

Maybe you could try with a freshly installed one of the above apache kafka distribution. If it works, I suppose it would, as it worked for me, there might be some interfering component/setup in your existing setup? If it also doesn't work with a fresh installation, let me know the exact version and the setup up that you used so that we can have a deeper look.

**Comment by mailvdutt** [comment]
PFA connect.log file, you will see that classes from ngdbc.jar are not
getting loaded from the plugins directory

ngdbc.jar jar file is valid and has the class com.sap.db.jdbc

***@***.*** kafka-connector-hana]$ pwd

/home/vdutt/confluent-7.2.1/plugins/kafka-connector-hana

***@***.*** kafka-connector-hana]$ java -jar ngdbc.jar -v

package com.sap.db.jdbc, JDBC, version 4.2, SAP HANA JDBC Driver, SAP SE,
2.13.9-ab103c64fa282b4db6cec549b07760e16c7fa79a

**Comment by elakito** [comment]
As I mentioned above, if you can reproduce this problem in a freshly installed setup, I can look into it. Otherwise, it is difficult to guess what is interfering the driver loading in your specific environment. Thanks.

**Comment by elakito** [comment]
not reproducible.

**Comment by nibroos** [comment]
first, im copying all of the plugin on Ddckerfile to these 2 directory. i've tried the example persons1db fresh still doesnt work.

Dockerfile:

```

FROM debezium/connect:2.7.3.Final
USER root:root

# Create directories for the connectors and dependencies
RUN mkdir -p /kafka/connect/kafka-connector-hana

# Copy the SAP HANA connector JAR files
COPY ./target/ /kafka/connect/kafka-connector-hana/
COPY ./target/ /kafka/connect

# Copy additional dependencies (guava and ngdbc)
COPY ./target/guava-31.0.1-jre.jar /kafka/connect/kafka-connector-hana/
COPY ./target/ngdbc-2.21.11.jar /kafka/connect/kafka-connector-hana/
```

docker-compose.yml

```
name: cdc-hana-exp-2

services:

  zookeeper:
    image: wurstmeister/zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    volumes:
      - zookeeper_data:/data
      - zookeeper_datalog:/datalog
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    depends_on:
      - zookeeper
    volumes:
      - kafka_data:/var/lib/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    environment:
      - DYNAMIC_CONFIG_ENABLED=true
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    ports:
      - 8085:8080
    depends_on:
      - kafka

  kconnect:
    image: debezium-connector-hana-min:latest
    ports:
      - 8083:8083
    environment:
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
      BOOTSTRAP_SERVERS: kafka:29092
      GROUP_ID: 1
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_REST_ADVERTISED_HOST_NAME: kconnect
      CONNECT_LOG4J_ROOT_LOGLEVEL: INFO
      CONNECT_PLUGIN_PATH: /kafka/connect,/kafka/connect/kafka-connector-hana,/kafka/connect/debezium-connector-hana,/kafka/connect/jdbc,/kafka/connect/kafka-connector-hana/scala3-library_3-3.3.3.jar,/kafka/connect/kafka-connector-hana/scala3-reflect_3-3.3.3.jar,/kafka/connect/kafka-connector-hana/scala3-stdlib_3-3.3.3.jar,/kafka/connect/kafka-connector-hana/scala-library-2.13.6.jar,/kafka/connect/kafka-connector-hana/scala-reflect-2.13.6.jar,/kafka/connect/kafka-connector-hana/ngdbc-2.21.11.jar,/kafka/connect/kafka-connector-hana/guava-31.0.1-jre.jar
    depends_on:
      - kafka
      - zookeeper
      - mysql
    volumes:
      - kconnect_data:/kafka/connect/data
      - ./custom-config:/kafka/custom-config

volumes:
  mysql_data:
  zookeeper_data:
  zookeeper_datalog:
  kafka_data:
  kconnect_data:
  custom-config:

networks:
  default:
    driver: bridge

```

The results when trying to connect:
```
 {
 name": "test-topic-1-source",
  "connector": {
    "state": "FAILED",
    "worker_id": "172.18.0.6:8083",
    "trace": "java.lang.NoClassDefFoundError: scala/Serializable\n\tat java.base/java.lang.ClassLoader.defineClass1(Native Method)\n\tat java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)\n\tat java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)\n\tat java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)\n\tat java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)\n\tat java.base/java.net.URLClassLoader$1.run
```
    
if someone had solve this, let me know
